### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by FFY00** [FFY00/meson-python#30]

**Comment by rgommers** [comment]
This is done and can be closed I think?

**Comment by rgommers** [comment]
Similar to gh-31: Things work fine on Windows and that is tested in CI. This issue was probably meant to describe only the unsupported corner case of having a standalone shared library packaged in the wheel, and then using an alternative to the Linux rpath handling to depend on it. That is already captured in the README, so I will close this issue. In case there's an actual real-world use case for that shared library feature on macOS, the person with the use case can open a new issue.
