### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by FFY00** [FFY00/meson-python#31]

**Comment by rgommers** [comment]
This is done and can be closed I think?

**Comment by rgommers** [comment]
Things work fine on macOS and that is tested in CI. This issue was probably meant to describe only the unsupported corner case of having a standalone shared library packaged in the wheel, and then using rpath handling to depend on it. That is already captured in the README, so I will close this issue. In case there's an actual real-world use case for that shared library feature on macOS, the person with the use case can open a new issue.
