### ISSUE TITLE
Choice of software license

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#61]
I didn't notice before that the current license currently is EUPL (European Union Public License). This is a weak-copyleft license, and it seems to prevent potentially incorporating code from this package in Meson itself (which is Apache 2.0), or any BSD/MIT licensed package (that includes most of the PyData ecosystem).

Is there a reason for this choice of license @FFY00?

**Comment by P-E-SCHMITZ** [comment]
The EUPL is, by decision C(2021) 8759 of the European Commission, the license covering all EC software distributions, but it is also used by a growing number of enterprises. It is not viral and compatible with a list of other copyleft licences. Code can by linked (even statically) with Apache or BSD components without impacting their licensing conditions. But when EUPL covered code is really merged into such components, the EUPL must cover the combined derivative if distributed to third parties. EUPL copyleft is rather strong (than weak) because most conditions (i.e. coverage of remote distribution and the obligation to provide access to source code) are persistent, even when a compatible license can be used for a derivative. Indeed, the compatible license prevails when its provisions are in conflict with those of the EUPL, which is rarely the case.
[EUPL Guidelines 2021 EN.pdf](https://github.com/FFY00/meson-python/files/8760849/EUPL.Guidelines.2021.EN.pdf)

**Comment by rgommers** [comment]
We discussed this, there's no reason for EUPL right now other than personal preference. Given that the Python ecosystem is mostly MIT/BSD, and that is the license that is also the most permissive for code reuse in Meson/SciPy/etc. So we're going to change to MIT.
